### ISSUE TITLE
Merge FTC, 3TC into xTC

### ISSUE THREAD

**Issue by KaimingTao** [hivdb/hivdb3-payload#1]
/cgi-bin/InhibitorsMutations.cgi?Gene=RT, "NRTI Received" selection list.
Merge FTC, 3TC into xTC

**Comment by philiptzou** [comment]
I think this is a query problem but not a database problem.

**Comment by KaimingTao** [comment]
@philiptzou I'm not sure where to put it. So I leave it here.

**Comment by philiptzou** [comment]
@KaimingTao Probably you should just send an email. There's no issue tracking system for the legacy code stored in CVS (perhaps we should migrate it to Git?)
